#!/bin/bash

set -e

read -p "Are you sure you want to reset the application? (y/n): " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    exit 1
fi

APP_ID=com.github.avojak.foreman
GSETTINGS_PATH=$APP_ID

print_setting () {
    echo -e "  \u2714 $1 = $(flatpak run --command=gsettings $APP_ID get $GSETTINGS_PATH $1)"
}

set_setting () {
    flatpak run --command=gsettings $APP_ID set $GSETTINGS_PATH $1 "$2"
    print_setting $1
}

clear_sqlite_table () {
    sqlite3 $DATABASE_PATH "DROP TABLE IF EXISTS $1;"
    echo -e "  \u2714 Cleared $1"
}

delete_files () {
    flatpak run --command=rm $APP_ID -rf $1
    echo -e "  \u2714 Removed $1"
}

echo
echo "Resetting GSettings…"

set_setting pos-x 360
set_setting pos-y 360
set_setting window-width 900
set_setting window-height 600

echo
echo "Resetting database..."

DATABASE_PATH=~/.var/app/$APP_ID/config/foreman.db

clear_sqlite_table servers
clear_sqlite_table server_executables

echo
echo "Deleting files…"

delete_files /var/config/server_executables/
delete_files /var/config/servers/

echo
echo -e "\033[1;32mDone\033[0m"
echo